name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v7
        with:
          go-version: '1.24'

      - name: Test broker
        run: |
          cd src/broker
          go vet ./...
          go test ./... -v

      - name: Test kwallet-secretd
        run: |
          cd src/kwallet-secretd
          go vet ./...
          go test ./... -v
